theme: minima
title: Charitha Nannapaneni's Blog
author: Charitha Nannapaneni
email: ncharitha26@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my final project for APCSA with Mr. Cohen. I am a very cool person, with very cool accomplishments.

# social links
github_username:  cnannapaneni # DO NOT include the @ character, or else the build will fail!
instagram_username: c.npanini
discord_username: charithahaha#9377

show_excerpts: true # set to false to remove excerpts on the homepage
